### PR TITLE
improve types so SortableElement/SortableContainer work w/ functional…

### PR DESCRIPTION
**Pull request by itsdaiego**
Improve types so SortableElement/SortableContainer work with functional components!

### CODE REVIEW

**Review by michael-adalo — APPROVED** [review]
✅

**Comment by itsdaiego** [comment]
[[Builder] - Add TypeScript](https://trello.com/c/pNd4D7YB/7-builder-add-typescript)

**Comment by itsdaiego** [comment]
[Fix field properties for collections](https://trello.com/c/68kzLCVK/23-fix-field-properties-for-collections)

**Comment by itsdaiego** [comment]
[Table doesn't clear properties from the previous collections that were connected](https://trello.com/c/cdifDVZK/5-table-doesnt-clear-properties-from-the-previous-collections-that-were-connected)

**Pull request merged**
